    // automatically generated by brainfreeze@mercury on 2016-03-03 - 
    // do NOT edit
    #ifndef _GENERATED_VERSION_H
    #define _GENERATED_VERSION_H
    char const * const VERSION = "0.1-V0.0-9-g47c20ba";
    #endif
