#!/bin/bash
action="$1"
version=$(cat "VERSION")
build=$(git describe --tags --always --long --dirty)
IFS=. read release minor <<< "$version"
if [ "$action" = "minor" ]; then
let "minor=minor+1"
fi
if [ "$action" = "release" ]; then
let "release=release+1"
fi
if [ "$action" = "print" ]; then
echo "$release.$minor-$build"
fi
echo "$release.$minor" > VERSION
if [ "$#" = 0 ]; then
echo "Version $release.$minor-$build"
echo "No action specified."
fi
cat > version.h <<-EOF
    // automatically generated by $(id -un)@$(hostname) on $(date +%F) - 
    // do NOT edit
    #ifndef _GENERATED_VERSION_H
    #define _GENERATED_VERSION_H
    char const * const VERSION = "${release}.${minor}-${build}";
    #endif
EOF
