    // automatically generated by thielen@art on 2016-03-08 - 
    // do NOT edit
    #ifndef _GENERATED_VERSION_H
    #define _GENERATED_VERSION_H
    char const * const VERSION = "0.1-Vsprint3-3-gf150931-dirty";
    #endif
